// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhjxsmVK4ulsBJKipX276jitCfLK_UJs',
    appId: '1:575192726483:web:2e07ceab1cc2bc20830d26',
    messagingSenderId: '575192726483',
    projectId: 'pandora-400014',
    authDomain: 'pandora-400014.firebaseapp.com',
    storageBucket: 'pandora-400014.appspot.com',
    measurementId: 'G-J3664D8QZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtvLXNEZR-husoRtId9d2aIfedaCdRdBM',
    appId: '1:575192726483:android:01c26730d51ea46d830d26',
    messagingSenderId: '575192726483',
    projectId: 'pandora-400014',
    storageBucket: 'pandora-400014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAejqp91uxfVO8bLuK0aLAOpIFqM4giZlM',
    appId: '1:575192726483:ios:4b4322c4b2d552d3830d26',
    messagingSenderId: '575192726483',
    projectId: 'pandora-400014',
    storageBucket: 'pandora-400014.appspot.com',
    iosClientId: '575192726483-q1d65s11b49c76eiojlhe0k12devqv26.apps.googleusercontent.com',
    iosBundleId: 'com.example.pandoraFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAejqp91uxfVO8bLuK0aLAOpIFqM4giZlM',
    appId: '1:575192726483:ios:cef5d9de36d021a9830d26',
    messagingSenderId: '575192726483',
    projectId: 'pandora-400014',
    storageBucket: 'pandora-400014.appspot.com',
    iosClientId: '575192726483-ahp9bclnlanhb85bps26ucttvcgo123k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pandoraFront.RunnerTests',
  );
}
