[default]
SECRET_KEY="5d2c5c09e23ad9f7dc0600259554cee595256644"
FIRESTORE_KEY="pandora-400014-firebase-adminsdk-qt38v-1c90cb0c54.json"
FIRESTORE_PROJECT="pandora-400014"
EXTENSIONS = [
    "app.blueprint.restapi",
    "app.ext.database"
]

[production]