version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pandora-backend:latestgit a
    container_name: backend
    env_file:
      - .env
    ports:
      - '5000:5000'
    restart: always
