version: '3.8'

services:
  pandora-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pandora-backend
    env_file:
      - .env
    ports:
      - '5000:5000'
    restart: always
